(()=>{
const stage=document.getElementById('stage'),slides=[...document.querySelectorAll('.slide')],lightbox=document.getElementById('lightbox'),reduced=matchMedia('(prefers-reduced-motion: reduce)');let current=0,animations=[],yt=null,ytReady=false,ytFailed=false,external=false,montage=0,flightFrame=0;
const localClips=['fusao','letras','tridimensional','sequencia','suporte','ramificacao'];const waiting=document.getElementById('waiting-video');
function fit(){stage.style.transform='translate(-50%,-50%) scale('+Math.min(innerWidth/1600,innerHeight/900)+')';}window.addEventListener('resize',fit);fit();
function soundVideo(){return lightbox.open&&lightbox.classList.contains('video-mode')?lightbox.querySelector('video'):slides[current].querySelector('video');}
function setExternal(value){external=!!value&&ytReady&&!ytFailed;document.getElementById('youtube-wrap').classList.toggle('active',external);document.getElementById('waiting-caption').textContent=external?'MÁQUINA EM AÇÃO · VÍDEO INDICADO':'EXCERTOS REAIS DO CURSO';if(external){waiting.pause();yt.playVideo?.();}else{yt?.pauseVideo?.();if(current===0)waiting.play().catch(()=>{});}}
function flight(){cancelAnimationFrame(flightFrame);if(slides[current].id!=='brasil-portugal')return;document.getElementById('flight-motion')?.remove();const plane=document.querySelector('.plane'),route=document.querySelector('.flight-route');if(reduced.matches){plane.style.display='none';return;}plane.style.display='';const length=route.getTotalLength(),start=performance.now();route.style.animation='none';function tick(now){const t=Math.min(1,(now-start)/7000);route.style.strokeDashoffset=String(1-t);const point=route.getPointAtLength(t*length),ahead=route.getPointAtLength(Math.min(length,t*length+2));const behind=route.getPointAtLength(Math.max(0,t*length-2));const angle=Math.atan2(ahead.y-behind.y,ahead.x-behind.x)*180/Math.PI;plane.setAttribute('transform','translate('+point.x+' '+point.y+') rotate('+angle+')');if(t<1&&slides[current].id==='brasil-portugal')flightFrame=requestAnimationFrame(tick);}tick(start);}
function go(index){if(lightbox.open)lightbox.close();animations.forEach(a=>a.cancel());animations=[];current=Math.max(0,Math.min(slides.length-1,index));slides.forEach((s,i)=>{s.hidden=i!==current;s.classList.toggle('active',i===current);});const active=slides[current];stage.dataset.tone=active.classList.contains('cream')||active.classList.contains('offer')?'light':'dark';document.getElementById('chapter-label').textContent=active.dataset.label;document.getElementById('slide-counter').textContent=String(current+1).padStart(2,'0')+' / '+slides.length;document.querySelector('.progress span').style.transform='scaleX('+((current+1)/slides.length)+')';history.replaceState(null,'','?slide='+(current+1));
document.querySelectorAll('video').forEach(v=>{if(!active.contains(v))v.pause();else if(v.hasAttribute('data-auto')||(v===waiting&&!external)){v.play().catch(()=>{});}});if(current!==0)yt?.pauseVideo?.();else if(external)yt?.playVideo?.();
if(!reduced.matches){active.querySelectorAll('.enter').forEach((node,i)=>animations.push(node.animate([{opacity:0,transform:'translateY(28px)'},{opacity:1,transform:'translateY(0)'}],{duration:800,delay:Math.min(i*80,450),easing:'cubic-bezier(.16,1,.3,1)',fill:'both'})));}flight();}
function togglePlay(){const v=soundVideo();if(current===0&&external){const state=yt?.getPlayerState?.();state===1?yt.pauseVideo():yt.playVideo();return;}if(v){if(v.paused)v.play().catch(()=>{});else v.pause();}}
window.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.target.closest?.('input,textarea,select'))return;const key=e.key.toLowerCase();if(lightbox.open){if(key==='escape')lightbox.close();if(key==='p')togglePlay();if(key==='m'){const v=soundVideo();if(v)v.muted=!v.muted;}return;}if(['arrowright','arrowdown','pagedown',' '].includes(key)){e.preventDefault();go(current+1);}else if(['arrowleft','arrowup','pageup'].includes(key)){e.preventDefault();go(current-1);}else if(key==='enter'&&current===0){e.preventDefault();go(1);}else if(key==='home'){e.preventDefault();go(0);}else if(key==='end'){e.preventDefault();go(slides.length-1);}else if(key==='f'){document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen().catch(()=>{});}else if(key==='p')togglePlay();else if(key==='m'){if(current===0&&external){yt?.isMuted?.()?yt.unMute():yt.mute();}else{const v=soundVideo();if(v)v.muted=!v.muted;}}else if(key==='r')flight();else if(key==='y'&&current===0)setExternal(!external);else if(key==='v'&&slides[current].id==='pratica'){lightbox.classList.add('video-mode');const v=lightbox.querySelector('video');v.src='media/letras.webm';v.muted=false;lightbox.showModal();v.play().catch(()=>{});}});
document.querySelectorAll('.photo img').forEach(img=>{img.tabIndex=0;img.setAttribute('role','button');img.setAttribute('aria-label','Ampliar: '+img.alt);const open=()=>{lightbox.classList.remove('video-mode');const full=lightbox.querySelector('img');full.src=img.src;full.alt=img.alt;lightbox.showModal();};img.addEventListener('click',open);img.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();open();}});});lightbox.addEventListener('click',e=>{if(e.target.tagName!=='VIDEO')lightbox.close();});lightbox.addEventListener('close',()=>lightbox.querySelector('video').pause());
const testimonial=document.getElementById('testimonial');testimonial.addEventListener('click',()=>{testimonial.paused?testimonial.play().catch(()=>{}):testimonial.pause();});['play','pause','ended'].forEach(evt=>testimonial.addEventListener(evt,()=>testimonial.parentElement.classList.toggle('playing',!testimonial.paused&&!testimonial.ended)));
document.querySelector('.wordmark').addEventListener('click',e=>{e.preventDefault();go(0);});let startX=null;stage.addEventListener('touchstart',e=>{if(e.target.closest('video,iframe,a,dialog'))return;startX=e.changedTouches[0].clientX;},{passive:true});stage.addEventListener('touchend',e=>{if(startX===null)return;const dx=e.changedTouches[0].clientX-startX;startX=null;if(Math.abs(dx)>60)go(current+(dx<0?1:-1));},{passive:true});
window.onYouTubeIframeAPIReady=()=>{yt=new YT.Player('youtube-player',{width:1600,height:900,videoId:'_0DybIH-lkE',playerVars:{autoplay:1,mute:1,controls:0,playsinline:1,rel:0,loop:1,playlist:'_0DybIH-lkE',origin:location.origin},events:{onReady:()=>{ytReady=true;yt.mute();if(current===0)yt.playVideo();},onStateChange:e=>{if(e.data===1&&current===0){external=true;document.getElementById('youtube-wrap').classList.add('active');document.getElementById('waiting-caption').textContent='MÁQUINA EM AÇÃO · VÍDEO INDICADO';waiting.pause();}},onError:()=>{ytFailed=true;setExternal(false);}}});};
const api=document.createElement('script');api.src='https://www.youtube.com/iframe_api';api.onerror=()=>{ytFailed=true;setExternal(false);};document.head.append(api);
setInterval(()=>{if(current!==0)return;if(!external&&ytReady&&!ytFailed&&montage%3===0){setExternal(true);}else{setExternal(false);montage++;waiting.src='media/'+localClips[montage%localClips.length]+'.webm';waiting.play().catch(()=>{});}},24000);
const hash=location.hash.slice(1);const target=hash?slides.findIndex(s=>s.id===hash):Number(new URLSearchParams(location.search).get('slide')||1)-1;go(Number.isFinite(target)&&target>=0?target:0);
})();

