(()=>{
const stage=document.getElementById('stage'),slides=[...document.querySelectorAll('.slide')],waiting=document.getElementById('waiting-video'),dialog=document.getElementById('media-dialog'),support=document.getElementById('support-video'),fullscreen=document.getElementById('fullscreen-button'),reduced=matchMedia('(prefers-reduced-motion: reduce)');
let current=0,flightFrame=0,yt=null,ytReady=false,ytFailed=false,external=false,montage=0,touchX=null;
const clips=['fusao','letras','tridimensional','sequencia','suporte','ramificacao'];
function fit(){stage.style.transform=`translate(-50%,-50%) scale(${Math.min(innerWidth/1600,innerHeight/900)})`;}
addEventListener('resize',fit);fit();
function soundVideo(){return dialog.open?support:slides[current].querySelector('video');}
function setExternal(value){external=!!value&&ytReady&&!ytFailed;document.getElementById('youtube-wrap').classList.toggle('active',external);document.getElementById('waiting-caption').textContent=external?'MÁQUINA EM AÇÃO':'EXCERTOS REAIS DO CURSO';if(external){waiting.pause();yt.playVideo?.();}else{yt?.pauseVideo?.();if(current===0)waiting.play().catch(()=>{});}}
function flight(){cancelAnimationFrame(flightFrame);if(slides[current].id!=='brasil-portugal')return;document.getElementById('flight-motion')?.remove();const plane=document.querySelector('.plane'),route=document.querySelector('.flight-route');if(reduced.matches){plane.style.display='none';route.style.strokeDashoffset='0';return;}plane.style.display='';const len=route.getTotalLength(),start=performance.now();function tick(now){const t=Math.min(1,(now-start)/3000);route.style.strokeDashoffset=String(1-t);const p=route.getPointAtLength(t*len),a=route.getPointAtLength(Math.min(len,t*len+2)),b=route.getPointAtLength(Math.max(0,t*len-2));plane.setAttribute('transform',`translate(${p.x} ${p.y}) rotate(${Math.atan2(a.y-b.y,a.x-b.x)*180/Math.PI})`);if(t<1&&slides[current].id==='brasil-portugal')flightFrame=requestAnimationFrame(tick);}tick(start);}
function go(index){if(dialog.open)dialog.close();cancelAnimationFrame(flightFrame);current=Math.max(0,Math.min(slides.length-1,index));slides.forEach((s,i)=>{s.hidden=i!==current;s.classList.toggle('active',i===current);s.setAttribute('aria-hidden',String(i!==current));});const s=slides[current];stage.dataset.slide=s.id;stage.dataset.tone=s.classList.contains('dark')?'dark':'light';document.getElementById('chapter-label').textContent=s.dataset.label;document.getElementById('slide-counter').textContent=String(current+1).padStart(2,'0')+' / '+slides.length;fullscreen.hidden=current!==0;history.replaceState(null,'','?slide='+(current+1));document.querySelectorAll('video').forEach(v=>{if(!s.contains(v))v.pause();else if(v.hasAttribute('data-auto')||(v===waiting&&!external))v.play().catch(()=>{});});if(current!==0)yt?.pauseVideo?.();else if(external)yt?.playVideo?.();if(!reduced.matches&&s.classList.contains('module')){s.getAnimations({subtree:true}).forEach(a=>a.cancel());s.querySelectorAll('.poster-title,.poster-hours,.poster-photo,.poster-screen,.poster-benefits').forEach((el,i)=>el.animate([{opacity:.65,transform:'translateY(12px)'},{opacity:1,transform:'translateY(0)'}],{duration:380,delay:i*55,easing:'cubic-bezier(.16,1,.3,1)'}));}flight();dispatchEvent(new CustomEvent('wilcom:slide',{detail:{id:s.id,index:current}}));}
function playPause(){if(current===0&&external&&!dialog.open){yt.getPlayerState()===1?yt.pauseVideo():yt.playVideo();return;}const v=soundVideo();if(v)v.paused?v.play().catch(()=>{}):v.pause();}
async function toggleFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{document.getElementById('status').textContent='O navegador não permitiu o ecrã inteiro. Usa F11.';}}
fullscreen.addEventListener('click',()=>{toggleFullscreen();fullscreen.blur();});document.addEventListener('fullscreenchange',()=>document.body.classList.toggle('fullscreen-active',!!document.fullscreenElement));
function openVideo(src,poster){support.src=src;support.poster=poster;support.muted=false;document.querySelectorAll('.slide video').forEach(v=>v.pause());yt?.pauseVideo?.();dialog.showModal();support.play().catch(()=>{});}
document.getElementById('close-media').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{support.pause();support.removeAttribute('src');support.load();const v=slides[current].querySelector('video[data-auto]');v?.play().catch(()=>{});if(current===0)setExternal(external);});dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.target.closest?.('input,textarea,select'))return;const k=e.key.toLowerCase();if(dialog.open){if(k==='p'){e.preventDefault();playPause();}if(k==='m')support.muted=!support.muted;return;}if((k==='enter'||k===' ')&&e.target.closest?.('a,button'))return;if(['arrowright','arrowdown','pagedown',' '].includes(k)){e.preventDefault();go(current+1);}else if(['arrowleft','arrowup','pageup'].includes(k)){e.preventDefault();go(current-1);}else if(k==='home'){e.preventDefault();go(0);}else if(k==='end'){e.preventDefault();go(slides.length-1);}else if(k==='enter'&&current===0){e.preventDefault();go(1);}else if(k==='f'){e.preventDefault();toggleFullscreen();}else if(k==='p')playPause();else if(k==='m'){if(current===0&&external)yt.isMuted()?yt.unMute():yt.mute();else{const v=soundVideo();if(v)v.muted=!v.muted;}}else if(k==='y'&&current===0)setExternal(!external);else if(k==='r'){if(slides[current].id==='oferta')window.wilcomOffer?.start();else flight();}else if(k==='t')openVideo('media/depoimento-aluna.mp4','media/aluna.jpg');else if(k==='v'&&slides[current].id==='wilcom')openVideo('media/letras.webm','media/letras.jpg');});
document.querySelector('.wordmark').addEventListener('click',e=>{e.preventDefault();go(0);});stage.addEventListener('touchstart',e=>{touchX=e.target.closest('video,iframe,a')?null:e.changedTouches[0].clientX;},{passive:true});stage.addEventListener('touchend',e=>{if(touchX===null)return;const d=e.changedTouches[0].clientX-touchX;touchX=null;if(Math.abs(d)>60)go(current+(d<0?1:-1));},{passive:true});
window.onYouTubeIframeAPIReady=()=>{yt=new YT.Player('youtube-player',{width:1600,height:900,videoId:'_0DybIH-lkE',playerVars:{autoplay:1,mute:1,controls:0,playsinline:1,rel:0,loop:1,playlist:'_0DybIH-lkE',origin:location.origin},events:{onReady:()=>{ytReady=true;yt.mute();if(current===0)yt.playVideo();},onStateChange:e=>{if(e.data===1){if(current!==0||dialog.open){yt.pauseVideo();return;}external=true;document.getElementById('youtube-wrap').classList.add('active');document.getElementById('waiting-caption').textContent='MÁQUINA EM AÇÃO';waiting.pause();}},onError:()=>{ytFailed=true;setExternal(false);}}});};
const api=document.createElement('script');api.src='https://www.youtube.com/iframe_api';api.onerror=()=>{ytFailed=true;setExternal(false);};document.head.append(api);setInterval(()=>{if(current!==0||dialog.open)return;if(!external&&ytReady&&!ytFailed&&montage%3===0)setExternal(true);else{setExternal(false);montage++;waiting.src='media/'+clips[montage%clips.length]+'.webm';waiting.play().catch(()=>{});}},24000);
reduced.addEventListener('change',flight);const hash=location.hash.slice(1),target=hash?slides.findIndex(s=>s.id===hash):Number(new URLSearchParams(location.search).get('slide')||1)-1;go(Number.isFinite(target)&&target>=0?target:0);
})();
